/* eslint-disable max-len */
import { Artist } from '../interfaces/Artist';

export const ARTISTS: Artist[] = [
  {
    id: 1, name: 'Becca Perret',
    photo:'../../assets/artists/becca-01.jpg',
    description: ['Becca Perret não tem apenas um nome incomum. Aos 25 anos, mulher, preta, natural da zona norte do Rio de Janeiro, a cantora e compositora expressa toda sua brasilidade e versatilidade de forma autêntica, misturando ritmos de MPB, Bossa e Groove, com grande influência do jazz, gospel e soul american.', 'Desde pequena, seus pais despertaram em Becca o interesse na música, que naturalmente foi fazendo parte de sua vida. Aos 15 anos, começou a cantar na igreja que frequentava. Quando completou 19 anos, ganhou uma bolsa para estudar teoria musical em uma faculdade de artes de Los Angeles (EUA). Foi quando teve a certeza de sua vocação e decidiu seguir a carreira artística.', 'Em 2020, Becca lançou seus primeiros trabalhos autorais de forma independente. Apesar de sua trajetória recente, a artista está presente em algumas das principais playlists digitais do país. Sua discografia já acumula mais de 5 milhões de plays no Spotify, com destaque para os singles “Seu”, em parceria com Lucas e Orelha, e “Contigo”, com Gabriel Gonti, que já ultrapassam 1 milhão de plays cada.', 'Em 2022, como nova integrante da Mousik, lançou os singles "Leve" e "Arte" e se prepara para lançar o seu primeiro projeto audiovisual intitulado "Na Becca". O primeiro EP do projeto, já lançado, trabalha um repertório de releituras nacionais. Já o segundo EP, que será lançado ainda esse ano, tem por objetivo unir música, arte e moda, e englobará desde singles autorais a releituras de sucessos.'],
    altText:'foto artista Becca Perret',
  },
  { id: 2,
    name: 'Rapha Lucas',
    photo:'../../assets/artists/raphalucas-01.jpg',
    description: ['Natural de Goiânia, Rapha Lucas se mudou ainda criança para o Rio de Janeiro com a família. Desde pequeno cantava e escrevia suas próprias letras e melodias. Filho do pastor e cantor gospel renomado Kléber Lucas, Rapha cresceu em uma família de músicos.', 'Por meio de vídeos postados na internet, surgiu a oportunidade de conhecer o cantor Fernando, da dupla Fernando & Sorocaba. Esse encontro resultou no início da carreira como compositor. Rapha tem canções gravadas por artistas, como Luan Santana, Thiaguinho, Sorriso Maroto, Dilsinho, Matheus & Kauan, Mumuzinho, Tierry, Marcos & Belutti, Zezé Di Camargo, entre outros.', 'Desde 2018, Rapha trabalha singles autorais. Em 2022, assinou com a nova agência Mousik para focar ainda mais em sua carreira e conquistar espaço na cena musical do Pop. Pela agência, lançou o EP “Ingênuo”, com 4 canções autorais e participações da dupla Lucas e Orelha e da cantora Mih.'],
    altText: 'foto artista Rapha Lucas',
  },
  {
    id: 3,
    name: 'Lucas & Orelha',
    photo:'../../assets/artists/lucaseorelha-01.jpg',
    description: ['A música foi o principal elo para a aproximação dos baianos Lucas e Orelha nos tempos de escola. Juntos, cantaram como backing vocals de bandas até que a amizade se transformou em parceria musical.', 'Em 2015, já como dupla, participaram e venceram a segunda edição do reality musical SuperStar, da Rede Globo. No mesmo ano, após vitória no programa, lançaram o single e clipe oficial de “Preta Perfeita”, seu maior sucesso autoral. Em 2016, lançaram seu primeiro álbum “Vamo Além”, com 14 canções autorais. Em 2018 e 2019, lançaram os EP’s “Marcas” e “Marcas II”, respectivamente, com releitura de clássicos, com destaque para “Sozinho”, na voz original de Caetano Veloso. Em 2020, em meio a pandemia, se reinventaram com publicação de mashups de sucessos nacionais e internacionais na internet, ganhando grande alcance digital.', 'Com mais de 300 milhões de streams nas plataformas, a dupla acumula, em sua carreira, parcerias com grandes nomes nacionais, como Dilsinho, Thiaguinho, Ferrugem, Leo Santana, Mumuzinho, Rashid, Rebecca, MC Marcinho e Buchecha.', 'Em 2022, o duo, que já flertava com o pagode desde a participação no reality, assinou com a Mousik e se firmou de vez no gênero, lançando seu primeiro DVD, intitulado “Lucas e Orelha Ao Vivo”, que já acumula mais de 2 milhões de streams e conta com participações especiais, como Turma do Pagode, Belo, Marvvila, Vitinho, Chininha, entre outros.'],
    altText: 'foto artista Lucas & Orelha',
  },
  {
    id: 4,
    name: 'Mih',
    photo:'../../assets/artists/mih-01.jpg',
    description: ['Mirella Pereira da Silva, ou Mih, é uma cantora e compositora, natural de Porto Alegre (RS). Filha de musicistas, seu primeiro contato com a música foi ainda criança. No colégio, ingressou no coral do Instituto de Arte para explorar seu talento musical.', 'Em 2019, foi descoberta por um artista local, o que resultou no primeiro convite para uma participação na música “Sul Acústico #2”. No mesmo ano, começou a trabalhar obras autorais. Durante a pandemia, a cantora começou a publicar covers na internet. O reconhecimento nas redes sociais veio logo no primeiro vídeo publicado, “Tudo no Sigilo”.', 'Em 2022, a cantora assina parceria com a Mousik, como uma das apostas da agência para a cena do Funk Pop. Seu primeiro lançamento “Chá de Sumiço”, ao lado de Jall e DJ 2F, se tornou um sucesso nas redes e atingiu 10 milhões de streams em apenas 3 meses. A faixa ganhou versão remix em Brega Funk, pelo DJ e influenciador Lucas Vrau. A cantora também lançou no ano “Propaganda”, ao lado da cantora Gabily e do DJ 2F, em resposta ao sucesso atual “Baile No Morro” do MC Tairon.'],
    altText: 'foto artista Mih',
  },
  {
    id: 5,
    name: 'Kamatos',
    photo:'../../assets/artists/kamatos-01.jpg',
    description: ['O violão que ganhou da avó, aos 12 anos, fez com que Karen Matos - mais conhecida pelo nome artístico Kamatos - se imaginasse cantando para uma multidão. Carioca da gema, dona de uma energia intensa e de alma livre e solar, começou a transformar suas vivências em letras e melodias aos 14 anos. Anos depois, com o suporte da família e amigos, decidiu estudar canto e dar início à carreira artística.', 'Em 2016, por meio de vídeos covers na internet, foi chamada para participar da produção do seu single de maior destaque “Our Way”, ao lado do DJ e produtor musical Ftampa. Hoje, o single soma mais de 30 milhões de streams. Em 2019, com a vontade de se conectar com público brasileiro, Ka passou a compor e lançar músicas em português.', 'Kamatos já se apresentou em palcos de grandes festivais ao lado de FTampa e WAO, como Festival Planeta Brasil, Ultra Music Festival e Rio Music Festival. Já foi, também, chamada para dividir palco com grandes cantores nacionais, como Vitão e Mumuzinho. Dentre suas apresentações solo, podemos destacar o Festival Planeta Tiradentes e o Campeonato Mundial de Wakeboard.','Em 2022, Kamatos assinou com a Mousik, sendo uma grande aposta da agência para a cena do pop nacional, com fortes influências do reggae e de brasilidades. No ano, lançou os singles autorais “Só Eu Que Faço”, “Dengo” e “La La Love”, esta última em colaboração com Vitin, vocalista do grupo Onze:20.'],
    altText: 'foto artista Kamatos',
  },
  {
    id: 6,
    name: 'DJ Will22',
    photo:'../../assets/artists/djwill22-01.jpg',
    description: ['Cria dos bailes de favela, no Rio de Janeiro, DJ Will22 - produtor musical, cantor e compositor - sempre teve facilidade em criar rimas e sonhava em ser MC, mas devido à dificuldade de investir nas produções começou a realizar seus próprios beats. Com 13 anos de carreira, 9 foram dedicados a ser DJ da Ludmilla, sendo responsável pela produção de alguns de seus maiores hits, incluindo “Não encosta" e “Socadona [Funk Remix]"", que juntos ultrapassam 100 milhões de streams.', 'Will também assina a produção de grandes sucessos, como “Onda Diferente” (Anitta), “Tô preocupada" (Rebecca) e “MC não é bandido" (MC Poze do Rodo). Outras collabs suas incluem artistas, como Kevin o Chris, MC Hariel, MC G15, Kaio Vianna, Gabily, MC Roba Cena e DJ 2F. Hoje, DJ Will22 soma mais de 500 milhões de streams em suas produções.', 'Dentre suas apresentações, podemos destacar o Baile da Favorita, o Nosso Camarote - camarote de prestígio na Sapucaí - e a Festa Planet, no Espaço Hall, no Rio de Janeiro. Em 2022, produziu o EP “Back to Be” da Ludmilla, em parceria com a nova agência Mousik - a qual assinou contrato no início do ano. Nessa nova fase, DJ Will22 quer consolidar sua carreira solo, firmando ainda mais seu nome no cenário do funk nacional.'],
    altText: 'foto artista DJ Will22',
  },
  {
    id: 7,
    name: 'Valesca Popozuda',
    photo:'../../assets/artists/valesca-01.jpg',
    description: ['Valesca dos Santos, mais conhecida como Valesca Popozuda, é um ícone do funk, sendo considerada uma das precursoras do gênero no início dos anos 2000. Nascida e criada em uma família humilde, no subúrbio carioca, trabalhou como frentista até entrar para a vida artística.', 'Foi como vocalista e fundadora do grupo “Gaiola das Popozudas” (2000 - 2012), que Valesca, em 2007, ganhou grande projeção nacional com os hits “Late Que Eu Tô Passando” e “Agora Sou Solteira”. Pelo grupo, fez turnês nacionais e internacionais (EUA e Europa).', 'Em 2012, Valesca anunciou sua saída para dedicar-se à carreira solo. Em 2013, lançou o hit nacional “Beijinho no Ombro”, com indicação às categorias de "Melhor Clipe” e "Música Chiclete" pelo Prêmio Multishow de Música Brasileira. Hoje, acumula mais de 100 milhões de views no clipe oficial, perdurando com relevância em plataformas digitais, programações de rádio e sets de festas nacionais.', 'Com carreira consolidada e de grande notoriedade, a cantora também carrega em sua discografia solo outros grandes sucessos, como “Sou dessas", “Mama", “Sou a diva que você quer copiar”, tema de campanha publicitária da marca de limpeza Veja, além de parcerias com outros artistas, como Mr. Catra, Rebecca, Claudia Leitte, MC TH, dentre outros.', 'Em 2022, a cantora assinou com a agência Mousik e se prepara para lançar o seu primeiro DVD. Seus singles mais recentessão “Calma Calma”, em parceria com o DJ 2F, e “Faz Direito”, com WC no Beat e Tati Quebra Barraco.'],
    altText: 'foto artista Valesca Popozuda',
  },
  {
    id: 8,
    name: 'DJ 2F',
    photo:'../../assets/artists/dj2f-01.jpg',
    description: ['Nascido e criado na comunidade Cidade de Deus, no Rio de Janeiro, Felipe Gomes de Souza ou DJ 2F - como é conhecido na cena musical - esbanja múltiplas influências do funk nacional. Com 8 anos de carreira e mais de 500 milhões de streams, o produtor musical, que é também cantor e compositor, assina hits marcantes e detém um catálogo com mais de 120 lançamentos.', 'DJ 2F tem colaborações com artistas consagrados, como Ferrugem, Ludmilla, Valesca Popozuda, MC G15, FP do Trem Bala, Gabily, MC Zaquin, MC Mirella, Davi Kneip, JS o Mão de Ouro, DJ Will22, entre outros.', 'Sua collab mais conhecida, “Gaiola É o Troco” (MC Du Black), soma mais de 200 milhões de streams e alcançou, em 2019, o 1º lugar no Spotify Brasil, além de ter entrado para o “Top 50 Portugal” e para a “Viral 50 Global”. Outras collabs de sucesso foram “Baile da Colômbia (Brega Funk) - Remix”, “Já Te Amei (170 Bpm) - Remix, “Modo Bird Box” e “Morena”, que somam mais de 100 milhões de streams.', 'Em 2022, produziu os projetos “Back to Be”, de Ludmilla (+20 milhões de streams) e o single “Chá de Sumiço", dos cantores Mih e Jall (+10 milhões de streams), ambos em parceria com a nova agência Mousik - a qual assinou contrato no início do ano.', 'DJ 2F pretende firmar cada vez mais seu espaço no funk nacional, explorando não apenas o talento como produtor musical, mas também diante dos palcos e câmeras. Com lançamentos a todo vapor, 2F promete trazer ainda mais novidades para esse ano, além de muitas parcerias de sucesso.'],
    altText: 'foto artista DJ 2F',
  },
  {
    id: 9,
    name: 'Gabily',
    photo:'../../assets/artists/gabily-01.jpg',
    description: ['Gabriela Batista, mais conhecida como Gabily, é uma cantora e compositora nascida no Rio de Janeiro. Gabily começou a cantar quando nova na igreja que frequentava. Em seu aniversário de 18 anos, foi convidada a subir no palco do grupo de pagode Tá Na Mente. A participação foi gravada e viralizou no Youtube, abrindo muitas portas para a cantora, que decidiu, a partir disso, seguir carreira artística.', 'Em 2016, lançou o seu primeiro EP “Deixa Rolar”. A faixa principal, com participação de Micael, foi sucesso nacional e alcançou o primeiro lugar nas rádios do Rio de Janeiro e de Salvador. O EP também contou com a participação de MC Maneirinho. Essas foram as primeiras de uma série de parcerias que Gabily acumulou ao longo de sua carreira, dentre elas: Ludmilla, Xamã, Rebecca, Clau, DJ Zullu, MC WM, FP do Trem Bala, MC G15, MC Zaquin, entre outros.', 'Em 2020, Gabily foi a artista nacional que mais lançou clipes, acumulando também mais de 10 milhões de streams no Spotify. Em 2021, lançou sua collab de maior sucesso, “Bilhete Premiado”, ao lado de Kevin o Chris e Mc Kevin, com mais de 30 milhões de streams, chegando a entrar no TOP 200 do Spotify Brasil.', 'Em 2022, a cantora assinou com a Mousik. Pela agência, lançou o single "Já Peguei, Quero Pegar" - faixa viral no TikTok - e, também, o EP “Mixtape da BadGirl” com 4 faixas, com participação de MC Mirella, DJ 2F e DJ Will22. Artista versátil, Gabily também dança e toca violão, teclado e bateria, sendo uma grande aposta da agência.'],
    altText: 'foto artista Gabily',
  },
  {
    id: 10,
    name: 'Jall',
    photo:'../../assets/artists/jall-01.jpg',
    description: ['Jall é um cantor, compositor e produtor musical, natural da Bahia. Filho do baixista e produtor da banda de axé Banda Mel, Jall tem conexão com a música desde muito novo. Em 2017, começou a gravar vídeos de suas composições na internet. Por meio deles, chamou a atenção de Luan, vocalista do duo UM44K, que o conectou aos seus produtores musicais na época.', 'A partir desse momento, Jall passou a compor músicas para diversos cantores renomados, como o próprio UM44K, Ferrugem, Lexa, Pocah, Whindersson Nunes, Rebecca, Pablo Vittar, entre outros.', 'Desde 2020, o cantor vem apostando em lançamentos, passeando pelo Funk e R&B, com parcerias, como MC Hariel, MC Jacaré, MC Mari, Kaio Viana, PK Delas, DJ 2F, DJ Will22, entre outros.', 'Em 2022, Jall assinou parceria com a nova agência Mousik para firmar sua carreira na música. Pela agência, lançou o single autoral “Chá de Sumiço”, que, em menos de 2 meses de lançamento, alcançou 10 milhões de streams. O single foi sucesso nas redes, ganhando versão remix brega funk pelo DJ e influenciador Lucas Vrau.'],
    altText: 'foto artista Jall',
  }
];
